name: testing

on:
  push:
    branches:
      - master

  workflow_dispatch:
    inputs:
      service:
        description: "Select the service to deploy"
        required: true
        default: service_1
        type: choice
        options:
          - service_1
          - service_2
          - service_3

jobs:
  services:
    runs-on: ubuntu-latest
    name: Prepare Services

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create archive for service_1
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.service == 'service_1' }}
        run: echo "Hello service_1"

      - name: Create archive for service_2
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.service == 'service_2' }}
        run: echo "Hello service_2"

      - name: Create archive for service_3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.service == 'service_3' }}
        run: echo "Hello service_3"
